# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# TODO: This is a placeholder. Run `nixos-generate-config` on the target machine
# and copy the generated hardware-configuration.nix here before the first build.
{ config, lib, pkgs, modulesPath, ... }:

{ }
