{ lib, ... }:

# Base/essential Flatpaks — from chezmoi's base.flatpak.Brewfile.
# Enabled per-host via `modules.flatpak.base.enable = true`.
{
  imports = [ ./default.nix ];

  modules.flatpak.base.packages = [
    "io.mpv.Mpv"
    "be.alexandervanhee.gradia"
    "ca.desrt.dconf-editor"
    "com.github.PintaProject.Pinta"
    "com.github.tchx84.Flatseal"
    "com.mattjakeman.ExtensionManager"
    "de.leopoldluley.Clapgrep"
    "io.github.bhack.mini-eq"
    "io.github.flattool.Ignition"
    "io.github.flattool.Warehouse"
    "io.github.kolunmi.Bazaar"
    "io.github.nokse22.high-tide"
    "io.github.pwr_solaar.solaar"
    "io.github.tanaybhomia.Whisp"
    "io.github.totoshko88.RustConn"
    "io.github.ungoogled_software.ungoogled_chromium"
    "io.missioncenter.MissionCenter"
    "it.mijorus.gearlever"
    "me.iepure.devtoolbox"
    "org.fedoraproject.MediaWriter"
    "org.gimp.GIMP"
    "org.gnome.Boxes"
    "org.gnome.Builder"
    "org.gnome.Calculator"
    "org.gnome.Calendar"
    "org.gnome.Characters"
    "org.gnome.Connections"
    "org.gnome.Decibels"
    "org.gnome.DejaDup"
    "org.gnome.FileRoller"
    "org.gnome.Firmware"
    "org.gnome.Logs"
    "org.gnome.Loupe"
    "org.gnome.Maps"
    "org.gnome.Nautilus"
    "org.gnome.NautilusPreviewer"
    "org.gnome.Papers"
    "org.gnome.SimpleScan"
    "org.gnome.Snapshot"
    "org.gnome.SoundRecorder"
    "org.gnome.TextEditor"
    "org.gnome.Weather"
    "org.gnome.baobab"
    "org.gnome.clocks"
    "org.gnome.font-viewer"
    "org.mozilla.firefox"
    "org.mozilla.thunderbird_esr"
    "page.tesk.Refine"
    "com.usebottles.bottles"
    "com.protonvpn.www"
    "com.rafaelmardojai.Blanket"
  ];
}
